name: Realiza o deploy em DEV

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Create /dev directory
      run: |
        mkdir -p dev
        mv * dev || true
        mv .[^.]* dev || true

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dev'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Realiza as migrações
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL_DEV }}
        SUPABASE_USER: ${{ secrets.SUPABASE_USER_DEV }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY_DEV }}
      run: |
        PGPASSWORD=$SUPABASE_KEY psql -h $SUPABASE_URL -p 6543 -d postgres -U $SUPABASE_USER -f migrations/migrate.sql
